-- AlterTable
ALTER TABLE `mod_actions` MODIFY `actionType` ENUM('KICK', 'BAN', 'UNBAN', 'MUTE', 'ROLE_ADD', 'ROLE_REMOVE', 'CHANNEL_LOCK', 'CHANNEL_UNLOCK', 'AUTOMOD_RULE_CREATE', 'AUTOMOD_RULE_DELETE', 'AUTOMOD_RULE_TOGGLE', 'AUTOMOD_RULE_KEYWORD_ADD', 'AUTOMOD_RULE_KEYWORD_REMOVE') NOT NULL;

